theme: jekyll-theme-chirpy
baseurl: ""
lang: en
timezone:
title: r0bsec # the main title
tagline: Cybersecurity fun and games # it will display as the sub-title
description: >- # used by seo meta and the atom feed
  Write-ups and notes for CTF's and bug hunting.
url: "https://r0bsec.github.io"
github:
  username: r0bsec # change to your github username
twitter:
  username: #twitter_username # change to your twitter username
social:
  name: r0bsec #your_full_name
  email: #example@domain.com # change to your email address
  links:
    - https://github.com/r0bsec
theme_mode: dark # [light|dark]
avatar: /assets/img/favicons/favicon-32x32.png
toc: true

assets:
  self_host:
    enabled: # boolean, keep empty means false
pwa:
  enabled: true # the option for PWA feature
paginate: 10
include:
  - pages
# ------------ The following options are not recommended to be modified ------------------
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  writeups:
    directory: _writeups/*/*
    output: true
    sort_by: order
    extensions: [md, txt, log, hash, *]

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: post
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: "" # An empty string here means all files in the project
      type: writeups
    values:
      layout: page
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      output: true
      author: r0bsec

  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
